### PR TITLE
since micro is no longer in the skyblock community

### PR DESCRIPTION
**Pull request by JosephE2**
I removed micro from coolPeople and replaced him with motor

micro is still super cool

### CODE REVIEW

**Comment by Lisenaaaa** [comment]
who is motor

**Comment by JosephE2** [comment]
motorgorrila1 the guy with dev role smartass

**Comment by Lisenaaaa** [comment]
the guy who has done literally nothing? ok

**Comment by jani270** [comment]
replace it with me

**Comment by SufferingSevereBrianDamage** [comment]
replace jani with me

**Comment by MicrocontrollersDev** [comment]
😭

**Pull request merged**
